"""empty message

Revision ID: 5d92512c641d
Revises: 9ddb6cb8777f
Create Date: 2018-12-29 22:10:26.057578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d92512c641d'
down_revision = '9ddb6cb8777f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
