"""empty message

Revision ID: 7228c2d45567
Revises: 6d1ef28b2fad
Create Date: 2018-12-29 21:34:47.335667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7228c2d45567'
down_revision = '6d1ef28b2fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
