"""empty message

Revision ID: e15b6cdfad5c
Revises: e8584c817914
Create Date: 2018-12-29 22:11:43.367847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15b6cdfad5c'
down_revision = 'e8584c817914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
